#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

ln -sf $OPENSHIFT_DATA_DIR/simple_store $OPENSHIFT_REPO_DIR/php/simple_store
ln -sf $OPENSHIFT_DATA_DIR/simple_cache $OPENSHIFT_REPO_DIR/php/simple_cache
